"""Draft request letters from a stored case.

A trace ends where an investigator's next step begins: a written request to
the exchange that holds the account, and, where USDT is involved, to Tether,
which can say why it froze an address and can freeze another. This module
turns a case into the first draft of those letters, filled with the facts the
case already holds -- the address to ask about, every hop with its amounts,
times and transaction hashes, and the evidence hash that ties the letter to
the sealed report.

It drafts; it does not decide. Everything that is the officer's to supply is
left as a marked blank: who is writing, the case and FIR reference, and the
legal provision the request is issued under. The tool suggests a provision in
brackets and never asserts one, because which power applies depends on the
case, the authority and the stage of the investigation.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from .report import _when

EXCHANGE = "exchange"
TETHER = "tether"
LETTERS = (EXCHANGE, TETHER)

BLANK = "[____________________]"
USDT_CHAINS = {"ethereum", "tron"}  # where USDT is Tether's own contract, with a blacklist


class LetterNotApplicable(ValueError):
    """The case holds nothing this letter could ask about."""


def _attribution(result: dict[str, Any]) -> dict[str, Any] | None:
    """The trace (original or follow-on) that reached an exchange, if any."""
    if result.get("exchange"):
        return {"trace": result, "asset": result.get("asset"), "via_swap": None}
    for follow in result.get("follow_ons") or []:
        found = follow.get("result") or {}
        if found.get("exchange"):
            return {"trace": found, "asset": follow.get("asset"), "via_swap": follow.get("swap")}
    return None


def _all_traces(result: dict[str, Any]) -> list[dict[str, Any]]:
    return [result] + [f["result"] for f in result.get("follow_ons") or [] if f.get("result")]


def _frozen(result: dict[str, Any]) -> list[dict[str, Any]]:
    return [m for t in _all_traces(result) for m in t.get("risk_matches") or [] if m.get("category") == "frozen"]


def _usdt_traces(result: dict[str, Any]) -> list[dict[str, Any]]:
    return [t for t in _all_traces(result) if t.get("asset") == "USDT" and t.get("chain") in USDT_CHAINS]


def available(result: dict[str, Any]) -> list[dict[str, str]]:
    """Which letters this case can support, for the interface to offer."""
    out = []
    found = _attribution(result)
    if found and result.get("direction", "outgoing") == "outgoing":
        out.append({"to": EXCHANGE, "title": f"Request to {found['trace']['exchange']}"})
    if _frozen(result) or _usdt_traces(result):
        out.append({"to": TETHER, "title": "Request to Tether"})
    return out


def _path_lines(trace: dict[str, Any], asset: str) -> list[str]:
    lines = []
    for step in (trace.get("trace_path") or [])[1:]:
        named = f" ({step['label']})" if step.get("label") else ""
        lines.append(
            f"  Hop {step.get('depth')}: {step.get('address')}{named}\n"
            f"         received {step.get('value_native', 0):,.6f} {asset} in "
            f"{step.get('tx_count', 0)} transfer(s), {_when(step.get('first_seen'))}"
            + (f" to {_when(step.get('last_seen'))}" if step.get("last_seen") != step.get("first_seen") else "")
        )
        hashes = step.get("tx_hashes") or []
        for tx in hashes[:10]:
            lines.append(f"         tx {tx}")
        if (step.get("tx_count") or 0) > len(hashes[:10]):
            lines.append(f"         (first {len(hashes[:10])} of {step.get('tx_count')} transfers shown; "
                         "all are listed in the attached report)")
    return lines


def _header(case_id: str, result: dict[str, Any], to_line: str, subject: str) -> list[str]:
    today = datetime.now(timezone.utc).strftime("%d %B %Y")
    manifest = (result.get("evidence") or {}).get("manifest_sha256")
    return [
        "DRAFT — for the investigating officer to review, complete and sign.",
        "Generated by Exchequer from a stored case. Nothing below has been sent.",
        "",
        f"From      : {BLANK} (name, rank, unit, official e-mail and phone)",
        f"Reference : {BLANK} (FIR / complaint / NCRP acknowledgement number)",
        f"Date      : {today}",
        f"To        : {to_line}",
        "",
        f"Subject   : {subject}",
        "",
        f"Exchequer case {case_id}, traced {str(result.get('created_at') or '').replace('T', ' ')[:16]} UTC,",
        f"{result.get('chain_name')} · asset {result.get('asset')} · reported address {result.get('address')}.",
        (f"Evidence manifest SHA-256: {manifest}" if manifest else
         "This case was stored before evidence hashing; the report says so."),
        "",
    ]


def _exchange_letter(case_id: str, result: dict[str, Any]) -> str:
    found = _attribution(result)
    if not found or result.get("direction", "outgoing") != "outgoing":
        raise LetterNotApplicable("This case reached no exchange, so there is no exchange to write to.")
    trace, asset = found["trace"], found["asset"]
    exchange, address = trace["exchange"], trace["exchange_address"]
    inferred = trace.get("attribution_inferred")
    swap = found["via_swap"]

    lines = _header(
        case_id, result,
        f"{exchange} — Law Enforcement / Compliance team {BLANK} (the exchange's published law-enforcement channel)",
        f"Request for account information relating to {'deposit ' if inferred or 'Dep' in (trace.get('exchange_label') or '') else ''}"
        f"address {address} ({result.get('chain_name')})",
    )
    lines += [
        "1. This office is investigating a complaint of cyber-enabled financial fraud. The",
        f"   victim reported the wallet address {result.get('address')}.",
        "",
        f"2. Public blockchain records show {asset} moving from that address to the address",
        f"   {address}, which {'we have reason to believe is a deposit address issued by' if inferred else 'is publicly labelled as belonging to'} {exchange}"
        + (f"\n   (label: {trace.get('exchange_label')})." if not inferred else "."),
    ]
    if inferred:
        dep = next((m for m in trace.get("inferred_deposits") or [] if m.get("address") == address), {})
        ev = dep.get("evidence") or {}
        lines += [
            f"   Every outgoing transfer from it ({ev.get('sweep_count', '?')} in all) went to {exchange}'s",
            f"   labelled wallet {ev.get('sweep_destination_label', '')} {ev.get('sweep_destination', '')},",
            "   the pattern of an exchange sweeping a customer deposit address.",
        ]
    if swap:
        lines += [
            "",
            f"   On the way, {swap.get('sender')} exchanged {swap.get('amount_in', 0):,.6f} {swap.get('asset_in')}",
            f"   for {asset} at {swap.get('router_label')} (tx {swap.get('tx')}); the {asset} was followed",
            "   from that swap.",
        ]
    lines += [
        "",
        "3. The transfers, hop by hop (all times UTC):",
        f"  Reported address: {trace.get('address')}",
        *_path_lines(trace, asset),
        "",
        f"4. In exercise of the powers under {BLANK}",
        "   [e.g. Section 94 of the Bharatiya Nagarik Suraksha Sanhita, 2023, and/or the",
        "   provisions of the PMLA, 2002 applicable to this investigation — officer to confirm],",
        f"   you are requested to furnish, in respect of the account(s) associated with {address}:",
        "   (a) the account holder's identity and KYC documents;",
        "   (b) the account statement and all deposits and withdrawals, with transaction hashes,",
        "       from the date of the first transfer above to date;",
        "   (c) linked bank accounts, UPI identifiers and cards used for fiat deposits or withdrawals;",
        "   (d) login records with IP addresses and device identifiers;",
        "   (e) any other deposit addresses issued to the same account.",
        "",
        "5. You are further requested to preserve all records relating to this account and to",
        f"   consider restricting withdrawals from it pending this investigation {BLANK}.",
        "",
        "6. This request identifies an address, not a person. The attached Exchequer report sets",
        "   out every address and transaction relied on, so each can be verified independently on",
        "   a public block explorer.",
        "",
        "Attachment: Exchequer report for case " + case_id + " (text), with evidence manifest.",
        "",
        f"{BLANK}",
        "(signature, name, designation, seal)",
    ]
    return "\n".join(lines) + "\n"


def _tether_letter(case_id: str, result: dict[str, Any]) -> str:
    frozen = _frozen(result)
    usdt = _usdt_traces(result)
    if not frozen and not usdt:
        raise LetterNotApplicable("This case involves no USDT on Ethereum or Tron and no Tether-frozen address.")

    lines = _header(
        case_id, result,
        f"Tether Operations Limited — law-enforcement requests team {BLANK} (Tether's published law-enforcement channel)",
        "Request for information and preservation relating to USDT addresses in a fraud investigation",
    )
    lines += [
        "1. This office is investigating a complaint of cyber-enabled financial fraud. The",
        f"   victim reported the wallet address {result.get('address')}.",
        "",
    ]
    n = 2
    if frozen:
        lines += [f"{n}. The following addresses in the traced funds are recorded on the USDT contract as",
                  "   frozen by Tether (AddedBlackList events):"]
        for m in frozen:
            lines += [f"   - {m.get('address')} — {m.get('label')}", f"     {m.get('source')}"]
        lines += ["", "   You are requested to state, to the extent you are able, the basis of each freeze and",
                  "   any information held on the parties associated with these addresses.", ""]
        n += 1
    for trace in usdt:
        found = trace.get("exchange")
        lines += [f"{n}. USDT on {trace.get('chain_name')} moved from {trace.get('address')} as follows (UTC):",
                  *_path_lines(trace, "USDT")]
        if found:
            lines.append(f"   It reached {found} at {trace.get('exchange_address')}.")
        lines.append("")
        n += 1
    lines += [
        f"{n}. In exercise of the powers under {BLANK}",
        "   [officer to state the provision and, if applicable, the mutual legal assistance route],",
        "   you are requested to preserve all records relating to the addresses above and to",
        f"   consider freezing USDT held at {BLANK} (addresses the officer confirms) pending this",
        "   investigation.",
        "",
        "Attachment: Exchequer report for case " + case_id + " (text), with evidence manifest.",
        "",
        f"{BLANK}",
        "(signature, name, designation, seal)",
    ]
    return "\n".join(lines) + "\n"


def draft(case_id: str, result: dict[str, Any], to: str) -> str:
    if to == EXCHANGE:
        return _exchange_letter(case_id, result)
    if to == TETHER:
        return _tether_letter(case_id, result)
    raise ValueError(f"Unknown letter '{to}'. Expected one of: {', '.join(LETTERS)}.")
